services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '9090:9090'
        environment:
            SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
            SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
            SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
        depends_on:
            - db

    db:
        image: postgres:17
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
            POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
